#!/bin/bash
#
# Get memcached version.
#
# VERSION       :0.1.0
# DEPENDS       :apt-get install netcat-openbsd
# LOCATION      :/usr/local/sbin/memcached-test.sh

set -e

echo "version" | nc -q 10 localhost 11211
